#This is an adventure/role-playing game for linux.
#Be sure to comment and leave pull requests!!!
var = 1
import os
import sys
clear = lambda:os.system('clear')
clear()
import time
print ('\033[1;32m +++Welcome to SUPER TREASURE HUNT!+++')
print ('\n')
time.sleep (3)
print ('In this game, you must read each paragraph and follow')
print ('the directions. Answer each question with one to two ')
print ('word answers. The choices are UPPERCASED. If you misspell') 
print ('anything, the game will restart. You are a treasure hunter.')
print ('You hear, that under the western ocean, there is a cave') 
print ('full of treasure and magical items.')
print ('\n')
while var== 1:
	ask1=input ('Are you ready to start the game?	')
	print ('\n')
	if ask1==('yes'):
		print ('You are in the center of a big city. Four roads')
		print ('lead out of the city. One goes NORTH, one goes ')
		print ('SOUTH, one goes EAST, and one goes WEST.')
		print ('\n')
		time.sleep (3)
		ask2=input ('Which one will you take?	')
		print ('\n')
		if ask2==('north'):
			print ('You are hit by a speeding horse. Better luck next time!')
			print ('\n')
			time.sleep (3)
		elif ask2== ('east'):
			print ('You are run over by a train. Sorry.')
			print ('\n')
			time.sleep (3)
		elif ask2== ('south'):
			print ('You start your journey south, riding your trusty horse,')
			print ('Jack. In the next town you pass through, you buy a currant')
			print ('map of the road systems. You see that you need to go west.')
			print ('\n')
			time.sleep (3)
			ask16=input ('Will you turn WEST now, or continue SOUTH?	')  
			print ('\n')
			if ask16== ('south'):
				print ('You choose to go south. Soon, you see a man running toward you')
				print ('he says there are bandits ahead. You do not lisen. Your horse ')
				print ('gets killed, and you get robbed. in your sorrow, you decide to ')
				print ('take up turkey farming. Tough luck!')
				print ('\n')
				time.sleep (3)
			elif ask16== ('west'):
				print ('You decide to go west. After three days, you spot the town you')
				print ('need to be in. This is a seaside town. You sell Jack, and buy a')
				print ('small fishing boat. Soon, you set sail in the west ocean. you ')
				print ('are suddenly caught in a whirlpool!')
				print ('\n')
				time.sleep (3)
				ask17=input ('Will you SWIM for it, or USE MAGIC to breath under water?	')
				print ('\n')
				if ask17== ('swim'):
					print ('You drown.')
					print ('\n')
					time.sleep (3)
				elif ask17== ('use magic'):
					print ('You are sucked to the bottom of the ocean. Then, you see')
					print ('the cave! You use magic to push you to the cave. Inside,')
					print ('you see a giant!')
					print ('\n')
					print ('"Halt! Those who wish to pass must answer me these questions')
					print ('three!!!"')
					print ('\n')
					time.sleep (3)
					ask18=input ('Answer questions?	')
					print ('\n')
					if ask18== ('yes'):
						ask19=input ('"What, is your name?"	')
						print ('\n')
						ask20=input ('"What, is your quest?"	')
						print ('\n')
						ask20=input ('"What, is your favorite color?"	')
						print ('\n')
						print ('"Oh stupid '+ask19+', who seeks the treasure, I find you not worthy!!!"')
						print ('You are killed. Better luck next time!')
						print ('\n')
						time.sleep (3)
					else:
						print ('Coward.')
						print ('\n')
						time.sleep (3)
		elif ask2==('west'):
			print ('You take the west road out of town. After a while')
			print ('of riding, your horse breaks down.')
			print ('\n')
			time.sleep (3)
			ask3=input ('Will you continue the HUNT on foot, or WAIT for passing horse to stop?	')
			print ('\n')
			if ask3==('hunt'):
				print ('You get off the stupid horse and blow it up with')
				print ('a bazooka. After you walk for a day, you go')
				print ('to sleep.')
				print ('\n')
				time.sleep (3)
				ask4=input ('When you wake, will you FOLLOW THE ROAD, or GO OFFROAD?	')
				print ('\n')
				if ask4== ('follow the road'):
					print ('You follow the road to a fork. One road goes')
					print ('NORTH, and one goes SOUTH.')
					print ('\n')
					time.sleep (3)
					ask5=input ('Which direction will you go?	')
					print ('\n')
					if ask5== ('north'):
						print ('You go north, and are stopped by bandits!')
						print ('\n')
						time.sleep (3)
						ask21=input ('Do you FIGHT them with your sword, or RUN?	')
						print ('\n')
						if ask21== ('fight'):
							print ('You are outnumbered. But you are experienced. You are killed.')
							print ('\n')
							time.sleep (3)
						elif ask21== ('run'):
							print ('You do not often run, but even you can see that you are out-')
							print ('numbered. Across fields and valley you dart. You use magic to')
							print ('make yourself faster. You soon outrun them. But now you are ')
							print ('lost. After wandering for four days, you see a man.')
							print ('\n')
							time.sleep (3)
							ask22=input ('Do you ASK for directions, or AVOID him?	')  
							print ('\n')
							if ask22== ('avoid'):
								print ('You avoid the man. But because of your stupidity, you starve.')
								print ('\n')
								time.sleep (3)
							elif ask22== ('ask'):

								print ('The man says there are no towns for miles around. But he invites')
								print ('you to come to his house to stay the night. After resupplying, you')
								print ('continue your mission. You soon find the road again. After two ')
								print ('more days, you get to a little seaside town. You get a boat, and ')
								print ('sail west. You get caught in a whirlpool!')
								print ('\n')
								time.sleep (3)
								ask23=input ('Will you HOLD your breath, or USE MAGIC to breath under water?	')
								print ('\n')
								if ask23== ('hold'):
									print ('You have drowned! Better luck next time!')
									print ('\n')
									time.sleep (3)
								elif ask23== ('use magic'):
									print ('You sink to the bottom of the ocean. Then you see the cave!!! ')
									print ('You use magic to move yourself toward the cave entrance. Suddenly,')
									print ('you are attacked by a giant! He is guarding the entrance!')
									print ('\n')
									time.sleep (3)
									ask24=input ('Do you FIGHT, or ask for a TRUCE?	')
									print ('\n')
									if ask24==('fight'):
										print ('You lose. Never fight a giant. (that is a tip. write it down)')
										print ('\n')
										time.sleep (3)
									elif ask24== ('truce'):
										print ('"You have invaded holy ground! For that, you must die!"')
										print ('\n')
										print ('The giant swings at you, and knocks your head off. Sucker!')
										print ('\n')
										time.sleep (3)
					elif ask5== ('south'):
						print ('you go south. Soon, you cross a river and refill')
						print ('your canteen. The day is hot, and you tire quickly.')
						print ('You fall asleep under a wide oak tree. You wake up')
						print ('as a prisoner of a tribe of cannibals. You are eaten')
						print ('At sunrise. Better luck nest time!')
						print ('\n')
						time.sleep (3)
				elif ask4== ('go offroad'):
					print ('You leave your campsite, pack your gear, and walk')
					print ('south. soon you come to a brook. You stop for a drink.')
					print ('Suddenly, a bear charges at you from the bushes.')
					print ('\n')
					time.sleep (3)
					ask6=input ('Will you draw your sword and FIGHT, or RUN for your life?	')
					print ('\n')
					if ask6== ('fight'):
						print ('In one quick slash, the bears head falls off.')
						print ('You are safe. You refill your canteen, and ')
						print ('continue the hunt. The day is hot, and you ')
						print ('take a nap. You wake a prisoner of cannibals.')
						print ('\n')
						time.sleep (3)
						ask7=input ('Will You MAKE A BREAK for it, or GET EATEN?	')
						print ('\n')
						if ask7== ('get eaten'):
							print ('You dummy! Why choose that?')
							print ('\n')
							time.sleep (3)
						elif ask7== ('make a break'):
							print ('You wait until they come to eat you, then you ')
							print ('jump the nearest guard, and grab your sword from')
							print ('him. You speak a magic word, and your sword catches')
							print ('fire. you scare off all the cannibals. You run for ')
							print ('the road, and continue your quest. You hit another')
							print ('fork.')
							print ('\n')
							time.sleep (3)
							ask8=input ('Will you go WEST, or EAST?	')
							print ('\n')
							if ask8==('east'):
								print ('You go east. The cannibals catch you and eat you. Sucks to be you!')
								print ('\n')
								time.sleep (3)
							elif ask8== ('west'):
								print ('You walk for three days, hunting and fishing for')
								print ('food. You see a town up ahead. On a hill above the')
								print ('the town, you see the sea. Now you know that your ')
								print ('quest is almost finished. You enter the town, and ')
								print ('make your way to the port. You look for a small boat')
								print ('to buy. You see one.')
								print ('\n')
								time.sleep (3)
								ask9=input ('Will you THREATEN the owner to sell, or USE MAGIC?	')
								print ('\n')
								if ask9== ('threaten'):
									print ('The owner kills you with a poisoned dagger. Better luck next time!')
									print ('\n')
									time.sleep (3)
								elif ask9== ('use magic'):
									print ('You use magic to make the owner sell you the boat. ')
									print ('You load your gear, and sail west. All you know is that')
									print ('the cave is under water. No one ever came back from look-')
									print ('ing for it. Your little craft suddenly gets caught in a ')
									print ('whirlpool. You go down.')
									print ('\n')
									time.sleep (3)
									ask10=input ('Do you HOLD YOUR BREATH, or USE MAGIC to breath under water?	')
									print ('\n')
									if ask10==('hold your breath'):
										print ('You could not hold it long enough. You drown. Sucker!')
										print ('\n')
										time.sleep (3)
									elif ask10== ('use magic'):
										print ('You continue to sink. You can not see the bottem of the')
										print ('ocean. Suddenly, a sea serpent appears. You can use your')
										print ('SWORD or FREEZE THE WATER around it.')
										print ('\n')
										time.sleep (3)
										ask11=input ('Choose wisely	')
										print ('\n')
										if ask11== ('sword'):
										 	print ('The drag from the water slows down your sword. You die.')
										 	print ('\n')
										 	time.sleep (3)
										elif ask11== ('freeze the water'):
											print ('You freeze the water around the serpent. It dies. You sink to')
											print ('the bottom of the ocean. You spot the cave. You use magic to')
											print ('move you towards the cave. Inside, the cave is dry. Magic')
											print ('holds the water back. Then, you see the treasure. You')
											print ('also see a giant. He is holding a club. The legend did not ')
											print ('say anything about a giant!')
											print ('\n')
											print ('"Halt! those who wish to pass must answer me these questions')
											print ('three!"')
											print ('\n')
											time.sleep (3)
											ask12=input ('Answer questions?	')
											print ('\n')
											if ask12== ('yes'):
												ask13=input ('"What, is your name?"	')
												print ('\n')
												ask14=input ('"What, is your quest?"	')
												print ('\n')
												ask15=input ('"What, is your favorite color?"	')
												print ('\n')
												print ('"Oh mighty '+ask13+', who seeks the treasure, I find you worthy!!!')
												print ('\n')
												print ('Spend it wisely!!!')
												print ('\n')
												time.sleep (10)
												sys.exit()
											else:
												print ('Coward.')
												print ('\n')
												time.sleep (3)
			
					elif ask6== ('run'):
						print ('You take off running. The bear stops, but you do not.')
						print ('You are tired from running, and take a nap. You wake ')
						print ('a prisoner of cannibals. You are eaten at sunrise.')	
						print ('\n')
						time.sleep (3)
			else:
				print ('You wait for a horse to stop. No horse does.')
				print ('You die of starvation.')
				print ('\n')
				time.sleep (3)
			
	else:
		print ('Loser!')
		time.sleep (10)
		sys.exit()
